/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekthotel;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author T.K
 */
public class PracownikSystem extends javax.swing.JFrame {

    List<Zlecenia> listaZlecen = null;

    List<Zlecenia> listaZleceniaNieprzyjete = new ArrayList<>();
    List<Zlecenia> listaZleceniaPrzyjete = new ArrayList<>();
    Pracownik pracwnik;
    DefaultTableModel modelNieprzyjete;
    DefaultTableModel modelPrzyjete;

    public PracownikSystem(Pracownik pracownik) {

        this.pracwnik = pracownik;
        initComponents();
        modelNieprzyjete = (DefaultTableModel) jTable2.getModel();
        modelPrzyjete = (DefaultTableModel) jTable3.getModel();
        aktualizuj();
        odswiez();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 530));
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista wszystkich zlecen");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 240, 217, 22);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nazwa", "typ", "cena", "dataRozpoczecia", "czasTrwania", "IdGoscia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 270, 650, 150);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Przyjete zlecenia");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 50, 130, 22);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pracownik");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 0, 230, 56);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Podejmij zlecenie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 440, 150, 40);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nazwa", "typ", "cena", "dataRozpoczecia", "czasTrwania", "IdGoscia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 80, 650, 150);

        jButton2.setText("Aktualizuj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 440, 150, 40);

        jButton3.setText("Wyloguj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 440, 150, 40);

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tlo.png"))); // NOI18N
        getContentPane().add(BACKGROUND);
        BACKGROUND.setBounds(0, 0, 700, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int test = 0;
        int z = jTable2.getSelectedRow();

        if (z != -1) {
            zajmijSie(z);
        }
    System.out.println("Zaznaczone: "+z);
        //commit();
        //aktualizuj();
        odswiez();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        aktualizuj();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowLogged().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracownikSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracownikSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracownikSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracownikSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    void aktualizuj() {

        try {

            DownloadZlecenia bombel = new DownloadZlecenia();
            ServerConnection.getInstance().getOutputStream().writeObject(bombel);
            listaZlecen = (List<Zlecenia>) ServerConnection.getInstance().getInputStream().readObject();

        } catch (IOException | ClassNotFoundException ex) {
        }

    }

    void zajmijSie(int id) {
        
        
        
      int idw = listaZleceniaNieprzyjete.get(id).getId();
      System.out.println("wybrano id="+idw);
      
     
        for (int i = 0; i < listaZlecen.size(); i++) {
             if (idw == listaZlecen.get(i).getId()) {
                 listaZlecen.get(i).setId_pracownik(pracwnik.getLogin());
               }
           }
        
        commit();
        aktualizuj();
        odswiez();
        
        
    }

    Zlecenia DajZlecenieoId(int index) {
        for (int i = 0; i < listaZlecen.size(); i++) {
            if (listaZlecen.get(i).getId() == index) {
                return listaZlecen.get(i);
            }
        }
        return null;
    }

    void usunWszystko(DefaultTableModel model) {

        int ilosc = model.getRowCount();
        for (int i = 0; i < ilosc; i++) {

            model.removeRow(0);
        }
    }

    void commit() {
        try {
            int stan;
            OdwzorujZlecenie bombel = new OdwzorujZlecenie(listaZlecen);

            ServerConnection.getInstance().getOutputStream().writeObject(bombel);
            //System.out.println("");           
            stan = (int) ServerConnection.getInstance().getInputStream().readObject();
            switch (stan) {
                case 0:
                    break;
                case -1:
                    JOptionPane.showMessageDialog(rootPane, "Blad tworzenie Zlecenia", "Blad", JOptionPane.ERROR_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(rootPane, "Blad!!!", "Blad", JOptionPane.ERROR_MESSAGE);
                    break;
            }

        } catch (IOException ex) {

        } catch (ClassNotFoundException ex) {

        }

    }

    void odswiez() {

        usunWszystko(modelNieprzyjete);
        usunWszystko(modelPrzyjete);
        listaZleceniaNieprzyjete.clear();
        listaZleceniaPrzyjete.clear();

        //model = (DefaultTableModel) jTable2.getModel();
        Object rowData[] = new Object[6];

        for (int i = 0; i < listaZlecen.size(); i++) {
            rowData[0] = listaZlecen.get(i).getNazwa();
            rowData[1] = listaZlecen.get(i).getTyp();
            rowData[2] = listaZlecen.get(i).getCena();
            rowData[3] = listaZlecen.get(i).getStringPoczatekOdwrocony();
            rowData[4] = listaZlecen.get(i).getCzasTrwania();
            rowData[5] = listaZlecen.get(i).getId_gosc();
            if (".".equals(listaZlecen.get(i).getId_pracownik())) {
                modelNieprzyjete.addRow(rowData);
                listaZleceniaNieprzyjete.add(listaZlecen.get(i));
            } else if (pracwnik.getLogin().equals(listaZlecen.get(i).getId_pracownik())) {
                modelPrzyjete.addRow(rowData);
                listaZleceniaPrzyjete.add(listaZlecen.get(i));
            } else {

            }

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
